### ISSUE TITLE
Normalization can skip WF

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust#100041]
I tried this code: [[playground]](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=c5cd930a4dee00e88a93712e13ee57e0)

```rust
trait WellUnformed {
    type RequestNormalize;
}

impl<T: ?Sized> WellUnformed for T {
    type RequestNormalize = ();
}

const _: <[[[[[[u8]]]]]] as WellUnformed>::RequestNormalize = ();
const _: <Vec<str> as WellUnformed>::RequestNormalize = ();
```

I expected this to error; `[[[[[[u8]]]]]]` is clearly not a well-formed type, as
> error[E0277]: the size for values of type `[u8]` cannot be known at compilation time
> = help: the trait `Sized` is not implemented for `[u8]`
> = note: slice and array elements must have `Sized` type

`Vec<str>` is perhaps even more cursed.

Instead: it compiles.

This is especially relevant for blanket/builtin traits which have associated types, such as `mem::Discriminant` and `ptr::Pointee`.

### Meta

1.64.0-nightly (2022-07-31 f9cba63746d0fff81625)

@rustbot label +A-associated-items

cc @eddyb who said this was
@rustbot label +I-unsound

**Comment by eddyb** [comment]
cc @rust-lang/types

**Comment by compiler-errors** [comment]
I think I found the bug. This is partly due to #90887 and partly due to us doing a `normalize` call before registering a `WellFormed` predicate in normalization code. Let me put up a PR.

**Comment by jackh726** [comment]
Is this fixed in #99217?

**Comment by compiler-errors** [comment]
Just checked out that PR, and it's not fixed by #99217.

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23100041.20Normalization.20can.20skip.20WF)).

@rustbot label -I-prioritize +P-high

**Comment by CAD97** [comment]
Status: still happens. #100046 is [blocked on implied bounds for unnormalized types](https://github.com/rust-lang/rust/pull/100046#issuecomment-1243953943).

**Comment by CAD97** [comment]
@rustbot label +I-ICE

I turned this into an ICE:

```rust
pub trait WellUnformed {
    type RequestNormalize;
}

impl<T: ?Sized> WellUnformed for T {
    type RequestNormalize = ();
}

pub fn latent(_: &[<[[()]] as WellUnformed>::RequestNormalize; 0]) {}

pub fn bang() {
    latent(&[]);
}
```

```text
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: error performing ParamEnvAnd { param_env: ParamEnv { caller_bounds: [], reveal: UserFacing, constness: NotConst }, value: ProvePredicate { predicate: Binder(WellFormed(&[<[[()]] as WellUnformed>::RequestNormalize; 0]), []) } }
  --> src\lib.rs:12:5
   |
12 |     latent(&[]);
   |     ^^^^^^^^^^^
   |
   = note: delayed at /rustc/7820972f866ca2cea281ccc39201c0cd27087110\compiler\rustc_trait_selection\src\traits\query\type_op\mod.rs:162:32
```
<details>

```
              0: std::backtrace::Backtrace::disabled
              1: std::backtrace::Backtrace::capture
              2: <rustc_errors::HandlerInner>::emit_diagnostic
              3: <rustc_borrowck::type_check::InstantiateOpaqueType as core::fmt::Debug>::fmt
              4: <rustc_borrowck::region_infer::values::PointIndex as core::ops::arith::Add<usize>>::add
              5: <rustc_borrowck::type_check::Locations>::span
              6: <rustc_middle::mir::syntax::Place as rustc_borrowck::place_ext::PlaceExt>::ignore_borrow
              7: <rustc_borrowck::constraints::OutlivesConstraintSet as core::ops::index::Index<rustc_borrowck::constraints::OutlivesConstraintIndex>>::index
              8: <rustc_borrowck::MirBorrowckCtxt>::consume_operand
              9: <rustc_middle::ty::adjustment::AutoBorrowMutability as rustc_mir_build::thir::cx::expr::ToBorrowKind>::to_borrow_kind
             10: rustc_query_impl::query_callbacks
             11: rustc_query_impl::query_callbacks
             12: rustc_query_impl::query_callbacks
             13: rustc_query_impl::profiling_support::alloc_self_profile_query_strings
             14: rustc_driver_impl::args::arg_expand_all
             15: rustc_interface::interface::parse_check_cfg
             16: rustc_interface::passes::analysis
             17: rustc_query_impl::profiling_support::alloc_self_profile_query_strings
             18: <tracing_subscriber::filter::directive::StaticDirective as core::default::Default>::default
             19: rustc_query_impl::profiling_support::alloc_self_profile_query_strings
             20: rustc_query_impl::profiling_support::alloc_self_profile_query_strings
             21: rustc_query_impl::profiling_support::alloc_self_profile_query_strings
             22: rustc_driver_impl::main
             23: rustc_driver_impl::main
             24: rustc_driver_impl::main
             25: rustc_driver_impl::main
             26: rustc_driver_impl::main
             27: std::sys::windows::thread::Thread::new
             28: BaseThreadInitThunk
             29: RtlUserThreadStart
```
</details>

```
note: rustc 1.72.0-nightly (7820972f8 2023-06-10) running on x86_64-pc-windows-msvc
```

Strangely enough, `fn latent` isn't enough to trigger an ICE; you need to call it. The error happens on `cargo check` and is pre-mono.

**Comment by compiler-errors** [comment]
lol, given the ICE message I thought it was a side-effect of #111918, but it ICEs on stable as well. --- well, better an ICE than unsoundness, eh?

**Comment by lcnr** [comment]
This is currently mostly fixable, except for types in impl headers.

As stated by @aliemjay in https://github.com/rust-lang/rust/pull/100046#issuecomment-1490361848, we can check unnormalized types for WF if the type is from an item signature.

We already use their unnormalized type when computing WF in borrowck, so we can first fix #105948 by using the unnormalized types from fn sigs.

We can then check the wf of function signatures without normalizing them.

**Comment by lcnr** [comment]
lowering this from P-high to P-medium as this cannot directly result in undefined runtime behavior by itself. Fixing this will be straightforward once we've imnplemented the better approach to handling implied bounds on binders, which is still a high priority as it also blocks other issues, such as #25860 and #84591.
