### ISSUE TITLE
error: internal compiler error: no errors encountered even though `delay_span_bug` issued broken MIR in DropGlue(DefId(2:2767 ~ core[178b]::ptr::drop_in_place)

### ISSUE THREAD

**Issue by andres-hurtado-lopez** [rust-lang/rust#101581]
### Code

```Rust
```

[code.zip](https://github.com/rust-lang/rust/files/9528613/code.zip)

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0-nightly (c2804e6ec 2022-09-07)
binary: rustc
commit-hash: c2804e6ec2c29a5c7368600ea173b890e2655c3d
commit-date: 2022-09-07
host: x86_64-unknown-linux-gnu
release: 1.65.0-nightly
LLVM version: 15.0.0

```

### Error output

258 |     std::fs::write( "email_carmelita.html", cuerpo );
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this `Result` may be an `Err` variant, which should be handled

warning: structure field `API_KEY` should have a snake case name
   --> src/utils/mod.rs:429:9
    |
429 |         API_KEY:String,
    |         ^^^^^^^ help: convert the identifier to snake case: `api_key`

error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: broken MIR in DropGlue(DefId(2:2767 ~ core[178b]::ptr::drop_in_place), Some(warp::hyper::server::conn::spawn_all::State<warp::tls::TlsStream, futures_util::future::Ready<std::result::Result<warp::hyper::service::util::ServiceFn<[closure@warp::TlsServer<warp::filter::recover::Recover<warp::log::internal::WithLog<[closure@warp::log::{closure#0}], warp::filters::BoxedFilter<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::fs::File,), (warp::fs::File,)>,), (warp::reply::WithHeader<reqwest::StatusCode>,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::fs::File,)>,), (warp::fs::File,)>,), (&str,)>,), (std::string::String,)>,), (std::string::String,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::fs::File,)>,), (warp::reply::sealed::Reply_,)>,)>>, fn(warp::Rejection) -> impl warp::Future<Output = std::result::Result<impl warp::Reply, std::convert::Infallible>> {routes::handle_rejection}>>::bind_ephemeral<([u8; 4], u16)>::{closure#1}::{closure#0}::{closure#0}], warp::hyper::Body>, std::convert::Infallible>>, warp::hyper::service::util::ServiceFn<[closure@warp::TlsServer<warp::filter::recover::Recover<warp::log::internal::WithLog<[closure@warp::log::{closure#0}], warp::filters::BoxedFilter<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::fs::File,), (warp::fs::File,)>,), (warp::reply::WithHeader<reqwest::StatusCode>,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::fs::File,)>,), (warp::fs::File,)>,), (&str,)>,), (std::string::String,)>,), (std::string::String,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::fs::File,)>,), (warp::reply::sealed::Reply_,)>,)>>, fn(warp::Rejection) -> impl warp::Future<Output = std::result::Result<impl warp::Reply, std::convert::Infallible>> {routes::handle_rejection}>>::bind_ephemeral<([u8; 4], u16)>::{closure#1}::{closure#0}::{closure#0}], warp::hyper::Body>, warp::hyper::common::exec::Exec, warp::hyper::server::conn::spawn_all::NoopWatcher>)) (after pass PhaseChange-Runtime(Optimized)) at bb3[0]:
                                Field projection `((*_1) as Connected).field[0]` specified type `warp::hyper::server::conn::upgrades::UpgradeableConnection<warp::tls::TlsStream, warp::hyper::service::util::ServiceFn<[closure@warp::TlsServer<warp::filter::recover::Recover<warp::log::internal::WithLog<[closure@warp::log::{closure#0}], warp::filters::BoxedFilter<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::fs::File,), (warp::fs::File,)>,), (warp::reply::WithHeader<reqwest::StatusCode>,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::fs::File,)>,), (warp::fs::File,)>,), (&str,)>,), (std::string::String,)>,), (std::string::String,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::fs::File,)>,), (warp::reply::sealed::Reply_,)>,)>>, fn(warp::Rejection) -> impl warp::Future<Output = std::result::Result<impl warp::Reply, std::convert::Infallible>> {routes::handle_rejection}>>::bind_ephemeral<([u8; 4], u16)>::{closure#1}::{closure#0}::{closure#0}], warp::hyper::Body>, warp::hyper::common::exec::Exec>`, but actual type is <warp::hyper::server::conn::spawn_all::NoopWatcher as warp::hyper::server::conn::spawn_all::Watcher<warp::tls::TlsStream, warp::hyper::service::util::ServiceFn<[closure@warp::TlsServer<warp::filter::recover::Recover<warp::log::internal::WithLog<[closure@warp::log::{closure#0}], warp::filters::BoxedFilter<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::fs::File,), (warp::fs::File,)>,), (warp::reply::WithHeader<reqwest::StatusCode>,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::fs::File,)>,), (warp::fs::File,)>,), (&str,)>,), (std::string::String,)>,), (std::string::String,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::fs::File,)>,), (warp::reply::sealed::Reply_,)>,)>>, fn(warp::Rejection) -> impl warp::Future<Output = std::result::Result<impl warp::Reply, std::convert::Infallible>> {routes::handle_rejection}>>::bind_ephemeral<([u8; 4], u16)>::{closure#1}::{closure#0}::{closure#0}], warp::hyper::Body>, warp::hyper::common::exec::Exec>>::Future
  |
  = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:128:36

error: internal compiler error: broken MIR in DropGlue(DefId(2:2767 ~ core[178b]::ptr::drop_in_place), Some(tokio::runtime::task::core::Stage<warp::hyper::server::conn::spawn_all::NewSvcTask<warp::tls::TlsStream, futures_util::future::Ready<std::result::Result<warp::hyper::service::util::ServiceFn<[closure@warp::TlsServer<warp::filter::recover::Recover<warp::log::internal::WithLog<[closure@warp::log::{closure#0}], warp::filters::BoxedFilter<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::fs::File,), (warp::fs::File,)>,), (warp::reply::WithHeader<reqwest::StatusCode>,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::fs::File,)>,), (warp::fs::File,)>,), (&str,)>,), (std::string::String,)>,), (std::string::String,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::fs::File,)>,), (warp::reply::sealed::Reply_,)>,)>>, fn(warp::Rejection) -> impl warp::Future<Output = std::result::Result<impl warp::Reply, std::convert::Infallible>> {routes::handle_rejection}>>::bind_ephemeral<([u8; 4], u16)>::{closure#1}::{closure#0}::{closure#0}], warp::hyper::Body>, std::convert::Infallible>>, warp::hyper::service::util::ServiceFn<[closure@warp::TlsServer<warp::filter::recover::Recover<warp::log::internal::WithLog<[closure@warp::log::{closure#0}], warp::filters::BoxedFilter<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::fs::File,), (warp::fs::File,)>,), (warp::reply::WithHeader<reqwest::StatusCode>,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::fs::File,)>,), (warp::fs::File,)>,), (&str,)>,), (std::string::String,)>,), (std::string::String,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::fs::File,)>,), (warp::reply::sealed::Reply_,)>,)>>, fn(warp::Rejection) -> impl warp::Future<Output = std::result::Result<impl warp::Reply, std::convert::Infallible>> {routes::handle_rejection}>>::bind_ephemeral<([u8; 4], u16)>::{closure#1}::{closure#0}::{closure#0}], warp::hyper::Body>, warp::hyper::common::exec::Exec, warp::hyper::server::conn::spawn_all::NoopWatcher>>)) (after pass PhaseChange-Runtime(Optimized)) at bb3[0]:
                                Field projection `((*_1) as Finished).field[0]` specified type `std::result::Result<(), tokio::task::JoinError>`, but actual type is std::result::Result<<warp::hyper::server::conn::spawn_all::NewSvcTask<warp::tls::TlsStream, futures_util::future::Ready<std::result::Result<warp::hyper::service::util::ServiceFn<[closure@warp::TlsServer<warp::filter::recover::Recover<warp::log::internal::WithLog<[closure@warp::log::{closure#0}], warp::filters::BoxedFilter<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::fs::File,), (warp::fs::File,)>,), (warp::reply::WithHeader<reqwest::StatusCode>,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::fs::File,)>,), (warp::fs::File,)>,), (&str,)>,), (std::string::String,)>,), (std::string::String,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::fs::File,)>,), (warp::reply::sealed::Reply_,)>,)>>, fn(warp::Rejection) -> impl warp::Future<Output = std::result::Result<impl warp::Reply, std::convert::Infallible>> {routes::handle_rejection}>>::bind_ephemeral<([u8; 4], u16)>::{closure#1}::{closure#0}::{closure#0}], warp::hyper::Body>, std::convert::Infallible>>, warp::hyper::service::util::ServiceFn<[closure@warp::TlsServer<warp::filter::recover::Recover<warp::log::internal::WithLog<[closure@warp::log::{closure#0}], warp::filters::BoxedFilter<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::fs::File,), (warp::fs::File,)>,), (warp::reply::WithHeader<reqwest::StatusCode>,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::fs::File,)>,), (warp::fs::File,)>,), (&str,)>,), (std::string::String,)>,), (std::string::String,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::fs::File,)>,), (warp::reply::sealed::Reply_,)>,)>>, fn(warp::Rejection) -> impl warp::Future<Output = std::result::Result<impl warp::Reply, std::convert::Infallible>> {routes::handle_rejection}>>::bind_ephemeral<([u8; 4], u16)>::{closure#1}::{closure#0}::{closure#0}], warp::hyper::Body>, warp::hyper::common::exec::Exec, warp::hyper::server::conn::spawn_all::NoopWatcher> as warp::Future>::Output, tokio::task::JoinError>
  |
  = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:128:36

error: internal compiler error: broken MIR in DropGlue(DefId(2:2767 ~ core[178b]::ptr::drop_in_place), Some(warp::hyper::server::conn::spawn_all::State<warp::hyper::server::conn::AddrStream, futures_util::future::Ready<std::result::Result<warp::hyper::service::util::ServiceFn<[closure@warp::Server<warp::filter::recover::Recover<warp::log::internal::WithLog<[closure@warp::log::{closure#0}], warp::filters::BoxedFilter<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::fs::File,), (warp::fs::File,)>,), (warp::reply::WithHeader<reqwest::StatusCode>,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::fs::File,)>,), (warp::fs::File,)>,), (&str,)>,), (std::string::String,)>,), (std::string::String,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::fs::File,)>,), (warp::reply::sealed::Reply_,)>,)>>, fn(warp::Rejection) -> impl warp::Future<Output = std::result::Result<impl warp::Reply, std::convert::Infallible>> {routes::handle_rejection}>>::bind_ephemeral<([u8; 4], u16)>::{closure#1}::{closure#0}::{closure#0}], warp::hyper::Body>, std::convert::Infallible>>, warp::hyper::service::util::ServiceFn<[closure@warp::Server<warp::filter::recover::Recover<warp::log::internal::WithLog<[closure@warp::log::{closure#0}], warp::filters::BoxedFilter<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::fs::File,), (warp::fs::File,)>,), (warp::reply::WithHeader<reqwest::StatusCode>,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::fs::File,)>,), (warp::fs::File,)>,), (&str,)>,), (std::string::String,)>,), (std::string::String,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::fs::File,)>,), (warp::reply::sealed::Reply_,)>,)>>, fn(warp::Rejection) -> impl warp::Future<Output = std::result::Result<impl warp::Reply, std::convert::Infallible>> {routes::handle_rejection}>>::bind_ephemeral<([u8; 4], u16)>::{closure#1}::{closure#0}::{closure#0}], warp::hyper::Body>, warp::hyper::common::exec::Exec, warp::hyper::server::conn::spawn_all::NoopWatcher>)) (after pass PhaseChange-Runtime(Optimized)) at bb3[0]:
                                Field projection `((*_1) as Connected).field[0]` specified type `warp::hyper::server::conn::upgrades::UpgradeableConnection<warp::hyper::server::conn::AddrStream, warp::hyper::service::util::ServiceFn<[closure@warp::Server<warp::filter::recover::Recover<warp::log::internal::WithLog<[closure@warp::log::{closure#0}], warp::filters::BoxedFilter<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::fs::File,), (warp::fs::File,)>,), (warp::reply::WithHeader<reqwest::StatusCode>,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::fs::File,)>,), (warp::fs::File,)>,), (&str,)>,), (std::string::String,)>,), (std::string::String,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::fs::File,)>,), (warp::reply::sealed::Reply_,)>,)>>, fn(warp::Rejection) -> impl warp::Future<Output = std::result::Result<impl warp::Reply, std::convert::Infallible>> {routes::handle_rejection}>>::bind_ephemeral<([u8; 4], u16)>::{closure#1}::{closure#0}::{closure#0}], warp::hyper::Body>, warp::hyper::common::exec::Exec>`, but actual type is <warp::hyper::server::conn::spawn_all::NoopWatcher as warp::hyper::server::conn::spawn_all::Watcher<warp::hyper::server::conn::AddrStream, warp::hyper::service::util::ServiceFn<[closure@warp::Server<warp::filter::recover::Recover<warp::log::internal::WithLog<[closure@warp::log::{closure#0}], warp::filters::BoxedFilter<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::fs::File,), (warp::fs::File,)>,), (warp::reply::WithHeader<reqwest::StatusCode>,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::fs::File,)>,), (warp::fs::File,)>,), (&str,)>,), (std::string::String,)>,), (std::string::String,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::fs::File,)>,), (warp::reply::sealed::Reply_,)>,)>>, fn(warp::Rejection) -> impl warp::Future<Output = std::result::Result<impl warp::Reply, std::convert::Infallible>> {routes::handle_rejection}>>::bind_ephemeral<([u8; 4], u16)>::{closure#1}::{closure#0}::{closure#0}], warp::hyper::Body>, warp::hyper::common::exec::Exec>>::Future
  |
  = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:128:36

error: internal compiler error: broken MIR in DropGlue(DefId(2:2767 ~ core[178b]::ptr::drop_in_place), Some(tokio::runtime::task::core::Stage<warp::hyper::server::conn::spawn_all::NewSvcTask<warp::hyper::server::conn::AddrStream, futures_util::future::Ready<std::result::Result<warp::hyper::service::util::ServiceFn<[closure@warp::Server<warp::filter::recover::Recover<warp::log::internal::WithLog<[closure@warp::log::{closure#0}], warp::filters::BoxedFilter<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::fs::File,), (warp::fs::File,)>,), (warp::reply::WithHeader<reqwest::StatusCode>,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::fs::File,)>,), (warp::fs::File,)>,), (&str,)>,), (std::string::String,)>,), (std::string::String,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::fs::File,)>,), (warp::reply::sealed::Reply_,)>,)>>, fn(warp::Rejection) -> impl warp::Future<Output = std::result::Result<impl warp::Reply, std::convert::Infallible>> {routes::handle_rejection}>>::bind_ephemeral<([u8; 4], u16)>::{closure#1}::{closure#0}::{closure#0}], warp::hyper::Body>, std::convert::Infallible>>, warp::hyper::service::util::ServiceFn<[closure@warp::Server<warp::filter::recover::Recover<warp::log::internal::WithLog<[closure@warp::log::{closure#0}], warp::filters::BoxedFilter<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::fs::File,), (warp::fs::File,)>,), (warp::reply::WithHeader<reqwest::StatusCode>,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::fs::File,)>,), (warp::fs::File,)>,), (&str,)>,), (std::string::String,)>,), (std::string::String,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::fs::File,)>,), (warp::reply::sealed::Reply_,)>,)>>, fn(warp::Rejection) -> impl warp::Future<Output = std::result::Result<impl warp::Reply, std::convert::Infallible>> {routes::handle_rejection}>>::bind_ephemeral<([u8; 4], u16)>::{closure#1}::{closure#0}::{closure#0}], warp::hyper::Body>, warp::hyper::common::exec::Exec, warp::hyper::server::conn::spawn_all::NoopWatcher>>)) (after pass PhaseChange-Runtime(Optimized)) at bb3[0]:
                                Field projection `((*_1) as Finished).field[0]` specified type `std::result::Result<(), tokio::task::JoinError>`, but actual type is std::result::Result<<warp::hyper::server::conn::spawn_all::NewSvcTask<warp::hyper::server::conn::AddrStream, futures_util::future::Ready<std::result::Result<warp::hyper::service::util::ServiceFn<[closure@warp::Server<warp::filter::recover::Recover<warp::log::internal::WithLog<[closure@warp::log::{closure#0}], warp::filters::BoxedFilter<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::fs::File,), (warp::fs::File,)>,), (warp::reply::WithHeader<reqwest::StatusCode>,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::fs::File,)>,), (warp::fs::File,)>,), (&str,)>,), (std::string::String,)>,), (std::string::String,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::fs::File,)>,), (warp::reply::sealed::Reply_,)>,)>>, fn(warp::Rejection) -> impl warp::Future<Output = std::result::Result<impl warp::Reply, std::convert::Infallible>> {routes::handle_rejection}>>::bind_ephemeral<([u8; 4], u16)>::{closure#1}::{closure#0}::{closure#0}], warp::hyper::Body>, std::convert::Infallible>>, warp::hyper::service::util::ServiceFn<[closure@warp::Server<warp::filter::recover::Recover<warp::log::internal::WithLog<[closure@warp::log::{closure#0}], warp::filters::BoxedFilter<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::generic::Either<(warp::fs::File,), (warp::fs::File,)>,), (warp::reply::WithHeader<reqwest::StatusCode>,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::reply::sealed::Reply_,)>,), (warp::fs::File,)>,), (warp::fs::File,)>,), (&str,)>,), (std::string::String,)>,), (std::string::String,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::reply::Json,)>,), (warp::fs::File,)>,), (warp::reply::sealed::Reply_,)>,)>>, fn(warp::Rejection) -> impl warp::Future<Output = std::result::Result<impl warp::Reply, std::convert::Infallible>> {routes::handle_rejection}>>::bind_ephemeral<([u8; 4], u16)>::{closure#1}::{closure#0}::{closure#0}], warp::hyper::Body>, warp::hyper::common::exec::Exec, warp::hyper::server::conn::spawn_all::NoopWatcher> as warp::Future>::Output, tokio::task::JoinError>
  |
  = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:128:36

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1494:13
stack backtrace:
   0:     0x7f4e2c56e210 - std::backtrace_rs::backtrace::libunwind::trace::hddd5e6b1b5e0cf84
                               at /rustc/c2804e6ec2c29a5c7368600ea173b890e2655c3d/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   1:     0x7f4e2c56e210 - std::backtrace_rs::backtrace::trace_unsynchronized::h1e30619f2b1dfc7e
                               at /rustc/c2804e6ec2c29a5c7368600ea173b890e2655c3d/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f4e2c56e210 - std::sys_common::backtrace::_print_fmt::h1c57dbed6b9e39aa
                               at /rustc/c2804e6ec2c29a5c7368600ea173b890e2655c3d/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f4e2c56e210 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h81e97128ef1d32f9
                               at /rustc/c2804e6ec2c29a5c7368600ea173b890e2655c3d/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f4e2c5c902e - core::fmt::write::h05bb200d128bd301
                               at /rustc/c2804e6ec2c29a5c7368600ea173b890e2655c3d/library/core/src/fmt/mod.rs:1202:17
   5:     0x7f4e2c55ecd5 - std::io::Write::write_fmt::hc8d8769ac02ad98c
                               at /rustc/c2804e6ec2c29a5c7368600ea173b890e2655c3d/library/std/src/io/mod.rs:1679:15
   6:     0x7f4e2c570e63 - std::sys_common::backtrace::_print::h7f10095fdc95f046
                               at /rustc/c2804e6ec2c29a5c7368600ea173b890e2655c3d/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f4e2c570e63 - std::sys_common::backtrace::print::hff7966088cd7ef66
                               at /rustc/c2804e6ec2c29a5c7368600ea173b890e2655c3d/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f4e2c570e63 - std::panicking::default_hook::{{closure}}::h5cfa206e6d48c088
                               at /rustc/c2804e6ec2c29a5c7368600ea173b890e2655c3d/library/std/src/panicking.rs:295:22
   9:     0x7f4e2c570b4f - std::panicking::default_hook::h75a6d8252dff2ced
                               at /rustc/c2804e6ec2c29a5c7368600ea173b890e2655c3d/library/std/src/panicking.rs:314:9
  10:     0x7f4e2edec9d1 - rustc_driver[4dbe72ff95e91a37]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f4e2c57169d - std::panicking::rust_panic_with_hook::h119231c709fbe31a
                               at /rustc/c2804e6ec2c29a5c7368600ea173b890e2655c3d/library/std/src/panicking.rs:702:17
  12:     0x7f4e2ff33221 - std[229541c32b9def22]::panicking::begin_panic::<rustc_errors[5d6420c66e5c3514]::ExplicitBug>::{closure#0}
  13:     0x7f4e2ff32d76 - std[229541c32b9def22]::sys_common::backtrace::__rust_end_short_backtrace::<std[229541c32b9def22]::panicking::begin_panic<rustc_errors[5d6420c66e5c3514]::ExplicitBug>::{closure#0}, !>
  14:     0x7f4e2ff32d36 - std[229541c32b9def22]::panicking::begin_panic::<rustc_errors[5d6420c66e5c3514]::ExplicitBug>
  15:     0x7f4e2ff358d6 - std[229541c32b9def22]::panic::panic_any::<rustc_errors[5d6420c66e5c3514]::ExplicitBug>
  16:     0x7f4e2e945f68 - <rustc_errors[5d6420c66e5c3514]::HandlerInner as core[178bf54443111ecd]::ops::drop::Drop>::drop
  17:     0x7f4e2dbf4bd8 - core[178bf54443111ecd]::ptr::drop_in_place::<rustc_session[54b7ccc2eea64ffd]::parse::ParseSess>
  18:     0x7f4e2dbb2f58 - <alloc[aa703239628d5152]::rc::Rc<rustc_session[54b7ccc2eea64ffd]::session::Session> as core[178bf54443111ecd]::ops::drop::Drop>::drop
  19:     0x7f4e2dbaff0d - core[178bf54443111ecd]::ptr::drop_in_place::<rustc_interface[14c34b33c6f785f8]::interface::Compiler>
  20:     0x7f4e2dbad73f - rustc_interface[14c34b33c6f785f8]::interface::create_compiler_and_run::<core[178bf54443111ecd]::result::Result<(), rustc_errors[5d6420c66e5c3514]::ErrorGuaranteed>, rustc_driver[4dbe72ff95e91a37]::run_compiler::{closure#1}>
  21:     0x7f4e2dbabc51 - <scoped_tls[c74ddbab68ad7cb1]::ScopedKey<rustc_span[ddb8e6977b977c82]::SessionGlobals>>::set::<rustc_interface[14c34b33c6f785f8]::interface::run_compiler<core[178bf54443111ecd]::result::Result<(), rustc_errors[5d6420c66e5c3514]::ErrorGuaranteed>, rustc_driver[4dbe72ff95e91a37]::run_compiler::{closure#1}>::{closure#0}, core[178bf54443111ecd]::result::Result<(), rustc_errors[5d6420c66e5c3514]::ErrorGuaranteed>>
  22:     0x7f4e2dbab93f - std[229541c32b9def22]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[14c34b33c6f785f8]::util::run_in_thread_pool_with_globals<rustc_interface[14c34b33c6f785f8]::interface::run_compiler<core[178bf54443111ecd]::result::Result<(), rustc_errors[5d6420c66e5c3514]::ErrorGuaranteed>, rustc_driver[4dbe72ff95e91a37]::run_compiler::{closure#1}>::{closure#0}, core[178bf54443111ecd]::result::Result<(), rustc_errors[5d6420c66e5c3514]::ErrorGuaranteed>>::{closure#0}, core[178bf54443111ecd]::result::Result<(), rustc_errors[5d6420c66e5c3514]::ErrorGuaranteed>>
  23:     0x7f4e2ec613b9 - <<std[229541c32b9def22]::thread::Builder>::spawn_unchecked_<rustc_interface[14c34b33c6f785f8]::util::run_in_thread_pool_with_globals<rustc_interface[14c34b33c6f785f8]::interface::run_compiler<core[178bf54443111ecd]::result::Result<(), rustc_errors[5d6420c66e5c3514]::ErrorGuaranteed>, rustc_driver[4dbe72ff95e91a37]::run_compiler::{closure#1}>::{closure#0}, core[178bf54443111ecd]::result::Result<(), rustc_errors[5d6420c66e5c3514]::ErrorGuaranteed>>::{closure#0}, core[178bf54443111ecd]::result::Result<(), rustc_errors[5d6420c66e5c3514]::ErrorGuaranteed>>::{closure#1} as core[178bf54443111ecd]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  24:     0x7f4e2c57b4f3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h36c6bf5e47e96783
                               at /rustc/c2804e6ec2c29a5c7368600ea173b890e2655c3d/library/alloc/src/boxed.rs:1940:9
  25:     0x7f4e2c57b4f3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h145bc1ef077d35d5
                               at /rustc/c2804e6ec2c29a5c7368600ea173b890e2655c3d/library/alloc/src/boxed.rs:1940:9
  26:     0x7f4e2c57b4f3 - std::sys::unix::thread::Thread::new::thread_start::h9922d7fa7807ef1d
                               at /rustc/c2804e6ec2c29a5c7368600ea173b890e2655c3d/library/std/src/sys/unix/thread.rs:108:17
  27:     0x7f4e2c287b27 - <unknown>
  28:     0x7f4e2c30a78c - <unknown>
  29:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.65.0-nightly (c2804e6ec 2022-09-07) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C opt-level=3 -C embed-bitcode=no

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
warning: `portal_proveedores_cana_carmelita` (bin "portal_proveedores_cana_carmelita") generated 400 warnings
error: could not compile `portal_proveedores_cana_carmelita`; 400 warnings emitted

```

<!--
Include a backtrace in the code block by setting `RUST_BACKTRACE=1` in your
environment. E.g. `RUST_BACKTRACE=1 cargo build`.
-->
<details><summary><strong>tcher> as warp::Future>::Output, tokio::task::JoinError>
  |
  = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:128:36

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1494:13
stack backtrace:
   0: std::panicking::begin_panic::<rustc_errors::ExplicitBug>
   1: std::panic::panic_any::<rustc_errors::ExplicitBug>
   2: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   3: core::ptr::drop_in_place::<rustc_session::parse::ParseSess>
   4: <alloc::rc::Rc<rustc_session::session::Session> as core::ops::drop::Drop>::drop
   5: core::ptr::drop_in_place::<rustc_interface::interface::Compiler>
   6: rustc_interface::interface::create_compiler_and_run::<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>
   7: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorGuaranteed>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorGuaranteed>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.65.0-nightly (c2804e6ec 2022-09-07) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C opt-level=3 -C embed-bitcode=no

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
warning: `portal_proveedores_cana_carmelita` (bin "portal_proveedores_cana_carmelita") generated 400 warnings
error: could not compile `portal_proveedores_cana_carmelita`; 400 warnings emitted
The authenticity of host 'prov_carmelita (144.202.38.244)' can't be established.
</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by compiler-errors** [comment]
This is fixed by #101437

**Comment by andres-hurtado-lopez** [comment]
After updating to : 

rustc 1.65.0-nightly (c2804e6ec 2022-09-07)
binary: rustc
commit-hash: c2804e6ec2c29a5c7368600ea173b890e2655c3d
commit-date: 2022-09-07
host: x86_64-unknown-linux-gnu
release: 1.65.0-nightly
LLVM version: 15.0.0


Compiled again and still the same issue. So what I finally did was to downgrade from TOKIO and it finally the compiler stopped chrashing:

`diff --git a/Cargo.toml b/Cargo.toml
index 8053de4..25a549c 100644
--- a/[Cargo.toml](http://cgit.grupojad.com.co/cgi-bin/cgit.cgi/portal_proveedores_carmelita_backend/tree/Cargo.toml?id=7d49b7b047772e33e0dc1fbd8ea45307c20f07da)
+++ b/[Cargo.toml](http://cgit.grupojad.com.co/cgi-bin/cgit.cgi/portal_proveedores_carmelita_backend/tree/Cargo.toml?id=142ed083d7ccdc077d1783f77a5cad53ded1c55e)
@@ -7,8 +7,8 @@ description = "Portal proveedores de Caña Carmelita. Servidor de aplicacion bac
 # See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
 
 [dependencies]
-warp = {version = "0.2.5", features = ["tls"] }
-tokio = { version = "0.2", features = ["full"] }
+warp = {version = "0.3.2", features = ["tls"] }
+tokio = { version = "1.21.0", features = ["full"] }
 futures-util = "0.3.8"
 serde = "1.0.116"
 serde_derive = "1.0.115"`
