### ISSUE TITLE
`ptr::read` unable to assume slice is always not null

### ISSUE THREAD

**Issue by AnsonYeung** [rust-lang/rust#106369]
Expects the following function to always return true since it's undefined behaviour otherwise.
```rs
use std::ptr;

pub unsafe fn test(s: &Vec<&[i32]>, idx: usize) -> bool {
    unsafe { Some(ptr::read(s.as_ptr().add(idx))).is_some() }
}
```

Actual result:
```asm
example::test:
        mov     rax, qword ptr [rdi + 8]
        shl     rsi, 4
        cmp     qword ptr [rax + rsi], 0
        setne   al
        ret
```

https://rust.godbolt.org/z/xzcTr15Yj
Causes #106368

**Comment by AnsonYeung** [comment]
This is caused by the function `ptr::read`, replacing it with deref produces the expected result.
```rs
use std::ptr;

pub unsafe fn test(s: &Vec<&[i32]>, idx: usize) -> bool {
    unsafe { Some(ptr::read(s.as_ptr().add(idx))).is_some() }
}

pub unsafe fn test_deref(s: &Vec<&[i32]>, idx: usize) -> bool {
    unsafe { Some(*(s.as_ptr().add(idx))).is_some() }
}
```
```asm
example::test:
        mov     rax, qword ptr [rdi + 8]
        shl     rsi, 4
        cmp     qword ptr [rax + rsi], 0
        setne   al
        ret

example::test_deref:
        mov     al, 1
        ret
```
https://rust.godbolt.org/z/7ajf9qs7b

**Comment by saethlin** [comment]
This looks a lot like https://github.com/rust-lang/rust/issues/93011 to me. `ptr::read` does a `copy_nonoverlapping` into a `MaybeUninit`, perhaps that wrapping also causes LLVM to lose the `nonnull`.

**Comment by Nilstrieb** [comment]
This can be minimized even further to just this
```rust
#[no_mangle]
pub unsafe fn bad(ptr: *const &i32) -> bool {
    unsafe { Some(ptr::read(ptr)).is_some() }
}
```
which on master emits (`rustc read.rs --crate-type=lib -Copt-level=3 --emit=asm`)
```asm
bad:
	.cfi_startproc
	cmpq	$0, (%rdi)
	setne	%al
	retq
```

This actually gets fixed by applying
```patch
diff --git a/compiler/rustc_codegen_llvm/src/abi.rs b/compiler/rustc_codegen_llvm/src/abi.rs
index a6fd2a7de6b..30006ac5e7b 100644
--- a/compiler/rustc_codegen_llvm/src/abi.rs
+++ b/compiler/rustc_codegen_llvm/src/abi.rs
@@ -81,7 +81,6 @@ fn should_use_mutable_noalias(cx: &CodegenCx<'_, '_>) -> bool {
             } else {
                 attrs.push(llvm::CreateDereferenceableOrNullAttr(cx.llcx, deref));
             }
-            regular -= ArgAttribute::NonNull;
         }
         for (attr, llattr) in OPTIMIZATION_ATTRIBUTES {
             if regular.contains(attr) {
```
which is weird, because this shouldn't change anything as `dereferenceable` implies `nonnull` (at least as far as I know and opts seem to rely on this).

With this applied, I now get
```asm
bad:
	.cfi_startproc
	movb	$1, %al
	retq
```
which is good.

But, this still doesn't help with the original example in the issue, which is the same with and without the patch.

**Comment by clubby789** [comment]
If we add a `!nonnull` when the slice pointer is loaded then the codegen looks better ([godbolt](https://llvm.godbolt.org/z/141MM3b81)). The IR before the generated assume isn't removed, but it codegens to a `mov al, 1; ret`

**Comment by clubby789** [comment]
It looks like the problem isn't the CopyNonOverlapping - rather, when building the load, the layout of MaybeUninit (used in `ptr::read`) is used, (even though we're loading from an `assume_init`), so we don't know of any niches. [godbolt](https://godbolt.org/z/xEvz19KTM)

**Comment by AnsonYeung** [comment]
After some more digging it seems the issue is reported back in 2020 in #73258 . Adding a layer of indirection of a function call seemingly fixed the case in there but it doesn't fix it for slice unfortunately.

```rs
pub unsafe fn indirect_read<T>(src: *const T) -> T {
    std::ptr::read(src)
}

pub unsafe fn test_ptr_read(s: *const &[i32]) -> bool {
    let x: &[i32] = unsafe { indirect_read(s) };
    Some(x).is_some()
}
```

https://godbolt.org/z/MTWEbsvvc

**Comment by scottmcm** [comment]
Test: https://github.com/rust-lang/rust/blob/master/tests/codegen/issues/issue-73258.rs
