### ISSUE TITLE
Cross-compiling to Windows is broken

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#12859]
(See later posts, `_Unwind_Resume` symbol is missing)

**Comment by steveklabnik** [comment]
I wonder, is this still true today?

**Comment by klutzy** [comment]
I think it's still true on 32-bit since the core issue is just that most distribution uses "common" unwinding (sjij) different to what we want (dwarf). (It's not a problem for 64-bit.)

**Comment by klutzy** [comment]
I'm still not sure what's the best action to close this. The "complete" fix is just to build cross gcc from scratch. The simplest fix is "let's add [fake sjij-unwinding support](https://github.com/rust-lang/rust/issues/12859#issuecomment-49246780)". We could add more proper sjlj support on Windows, but I'm not sure how meaningful it is.

**Comment by vadimcn** [comment]
@klutzy, what makes it "fake"?  

But yeah, the bigger question is: Do we have a compelling reason for supporting SjLj in addition to Dwarf on win32?
Can we simply tell Linux cross-builders to use dwarf-based mingw?

**Comment by jan-hudec** [comment]
Does that mean the Windows MinGW builds use different configuration than the Linux cross-compilers for the same target?

**Comment by vadimcn** [comment]
MinGW is available in both flavors, but we only support the dwarf one.

**Comment by Fedcomp** [comment]
> Do we have a compelling reason for supporting SjLj in addition to Dwarf on win32?
Just curious, what would it take to add SjLj support? a LOT of work?

**Comment by hone** [comment]
Hi, I was wondering if there was an update on this issue. Ideally, I'd like to not rebuild gcc from scratch. I'm interested in rust to be used with mruby and particularly with setting up a cross compiling toolchain from linux -> 32/64 bit osx and winodws. I believe I've run into the same issue with trying to build target `i686-pc-windows-gnu`. This is the [error](https://t.co/FuDCRq24RT) I'm seeing. Thanks!

**Comment by vadimcn** [comment]
Compatibility with Windows mingw builds and bitrot aside, the main sticking point, as I recall, was figuring out which mingw flavor we have during the compilation of some std::rt modules. 
The optimal place to do this would be in the configure script, but since `is_sjlj` flag needs to be per-target, we need to crate a mapping `target` : `is_sjlj` and pass it down to make.   And given the [non-existent] level of support of maps in bash and make, it didn't seem a good investment of my time to make it all work...

**Comment by alexcrichton** [comment]
@vadimcn note that with https://github.com/rust-lang/rust/pull/30448 I believe it should enable us to transition the MinGW targets over to using the SEH exceptions in which case we'll drop all MinGW dependencies and you should be able to use any toolchain to link Windows Rust code (I think)

**Comment by alexcrichton** [comment]
I'm going to close this as basically "there's nothing we can do here". Cross compiling works for x86_64 where we don't depend on the style of unwinding of the MinGW toolchain, but we can only cross compiling to a MinGW toolchain targeting dwarf exceptions on 32-bit. Unfortunately the toolchains on Linux tend to be SjLj based, but that's just not the binaries we ship for libstd.

**Comment by jan-hudec** [comment]
@alexcrichton, so what happened to the SEH plan from #30448? Is it not possible for the 32-bit gnu target after all?

**Comment by alexcrichton** [comment]
Unfortunately there's a combination of:

1) LLVM doesn't support that
2) The MinGW linker somehow produces an invalid binary

(1) may be surmountable but I couldn't make heads or tails of (2) unforutnately :(

**Comment by Arnaz87** [comment]
Hi, i'm new to rust, and with what I understood of this thread (not that much), I fixed it adding the option `-C panic=abort`, which as I understand, disables exception handling and just aborts the program on error, and avoids all these problems about incompatible unwinding systems.

**Comment by saurik** [comment]
I don't think I've ever seen a distribution-shipped version of MinGW that was configured to _not_ use SJLJ exception handling for 32-bit. In fact, it is so rare, I wasn't even aware it existed as an upstream-supported option. If you are going to hard-code a specific variant, you should hard-code SJLJ for 32-bit, or Rust essentially becomes arbitrarily incompatible with the entire rest of the MinGW ecosystem. Like, this is _six years_ after this bug was filed, and I can report that everyone is still using SJLJ, AFAIK no one is talking about changing that, and Rust thereby still fails to compile 32-bit binaries for Windows. :(

**Comment by mati865** [comment]
@saurik Fedora ships Dwarf-2 i686 MinGW toolchain, basically all popular native Windows MinGW toolchains also default to Dwarf-2.
Also there is performance overhead when using SJLJ.

**Comment by saurik** [comment]
@mati865 Ok, you know what? I'm sorry.  FWIW, both Ubuntu and macOS Homebrew are shipping SJLJ, which is why I'm still experiencing this bubble of SJLJ whenever I do any tests, as those are the operating systems I normally work with; it turns out you are right: the packages on repo.msys2.org, which is what I'd consider the official decision at this point, are using Dwarf-2.

…and what's weird is that _my own projects_ are also using Dwarf-2, and I simply didn't notice, as I'm actually using clang to do my Win32 compilation right now, and it is, in fact, generating Dwarf-2. This is where I was just really dumb: I put the math together all wrong here and came to the wrong conclusions about what toolchains were doing what. While "basically all popular" still doesn't seem quite right (and you actually said the opposite multiple times in #49078... ;P), it certainly is _morally_ correct, so again: I'm sorry.

The issue I'm experiencing is really then just an issue overriding the sysroot of the linker, and I'll take the comments over to cargo.

**Comment by mati865** [comment]
> While "basically all popular" still doesn't seem quite right (and you actually said the opposite multiple times

I might have not been clear enough. I wanted to say "toolchains running on the Windows natively", Linux distros indeed mostly ship SJLJ based toolchain for i686.

This issue is far beyond https://github.com/rust-lang/rust/issues/68887. It'd require adding rustc argument to switch between DWARF-2 and SJLJ, then you'd have to use [build-std](https://doc.rust-lang.org/cargo/reference/unstable.html#build-std), xargo or cargo-xbuild to build std library with chosen exception handling. Another solution would be adding new i686 target triple which would use only SJLJ.

**Comment by zzeroo** [comment]
For a project of mine I hit this error. I can't belive this issue dates from 2014 RLY?

https://gist.github.com/zzeroo/2f4168364eda226c7ec808a9153ad472

I try to set up a cross compilation environment to compile win32 binaries from a linux box. For separation I use docker containers, sorry that's all I can do to simplify the problem. Please see: https://gitlab.com/zzeroo/rust-crosspile the Dockerfile describes my setup: https://gitlab.com/zzeroo/rust-crosspile/-/blob/master/Dockerfile

This are the steps to get to the error
```bash
git clone https://gitlab.com/zzeroo/rust-crosspile -b i686
cd rust-crosspile
docker build . -t rust-crosspile

cd /tmp
cargo build --bin hello-world 
cd example 
docker create -v `pwd`:/home/rust/src --name HELLO-build rust-crosspile:latest
docker start -ai HELLO-build
```

**Comment by mati865** [comment]
@zzeroo it's your distribution issue.
It's fixed in Fedora 32 but `fedora:latest` in your Dockerfile still points to Fedora 31 according to this page: https://hub.docker.com/_/fedora?tab=description

**Comment by zzeroo** [comment]
@mati865 thank you for this fast help. Sorry for that stupid question.

**Comment by infinity0** [comment]
I am hitting this issue when trying to cross-compile from linux to 32-bit windows.

@mati865 if I patch `src/libpanic_unwind/dwarf/eh.rs` so that `USING_SJLJ_EXCEPTIONS` is `true` on 32-bit windows, do you see any potential issues resulting from this? As I understand, there should be no issues about compatibility between a linux-host rustc vs a windows-host rustc, since rust puts the metadata hash in the library name, so it is unlikely that someone will accidentally link two libraries together built using different unwinding strategies (if they did give -C prefer-dynamic)?

**Comment by infinity0** [comment]
Never mind, I found [this PR and comment](https://github.com/rust-lang/rust/pull/55444#issuecomment-434044002) which explains why my intended approach would not be feasible (and it's also not as simple as setting that flag).
