### ISSUE TITLE
ICE with arduino

### ISSUE THREAD

**Issue by coolCucumber-cat** [rust-lang/rust#139223]
### Output

```bash
$ cargo build --release --target=avr-specs/avr-atmega328p.json
   Compiling compiler_builtins v0.1.152
   Compiling core v0.0.0 (/home/sven/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core)
   Compiling proc-macro2 v1.0.94
   Compiling unicode-ident v1.0.18
   Compiling syn v1.0.109
   Compiling paste v1.0.15
   Compiling embedded-hal-bus v0.1.0
   Compiling quote v1.0.36
   Compiling ufmt-macros v0.3.0
   Compiling avr-device-macros v0.7.0
   Compiling rustc-std-workspace-core v1.99.0 (/home/sven/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-core)

thread 'rustc' panicked at compiler/rustc_codegen_ssa/src/back/metadata.rs:356:17:
compiler/rustc_codegen_ssa/src/back/metadata.rs:356:17: AVR CPU not explicitly specified
stack backtrace:
   0:     0x7e247b879b33 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::he2e6b0ecdb05c607
   1:     0x7e247c006051 - core::fmt::write::h610626c1c60da77c
   2:     0x7e247d466a91 - std::io::Write::write_fmt::h4e33684eb50b719c
   3:     0x7e247b879992 - std::sys::backtrace::BacktraceLock::print::h72b1875ec3ad25c3
   4:     0x7e247b87d47a - std::panicking::default_hook::{{closure}}::h2eb086ab7d432499
   5:     0x7e247b87cfff - std::panicking::default_hook::h4e505796ed0a3f8c
   6:     0x7e247a8f32b0 - std[33b37f4690323d4d]::panicking::update_hook::<alloc[b734503c5a26a59b]::boxed::Box<rustc_driver_impl[b04f6af5afbf5cf5]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7e247b87dcf3 - std::panicking::rust_panic_with_hook::h9e05a4a2b6a4fcb3
   8:     0x7e247aee70b2 - std[33b37f4690323d4d]::panicking::begin_panic::<alloc[b734503c5a26a59b]::string::String>::{closure#0}
   9:     0x7e247aee2326 - std[33b37f4690323d4d]::sys::backtrace::__rust_end_short_backtrace::<std[33b37f4690323d4d]::panicking::begin_panic<alloc[b734503c5a26a59b]::string::String>::{closure#0}, !>
  10:     0x7e247aedd907 - std[33b37f4690323d4d]::panicking::begin_panic::<alloc[b734503c5a26a59b]::string::String>
  11:     0x7e247af73477 - rustc_middle[33747cc028c37340]::util::bug::opt_span_bug_fmt::<rustc_span[174cbf46716f164]::span_encoding::Span>::{closure#0}
  12:     0x7e247af4ef8a - rustc_middle[33747cc028c37340]::ty::context::tls::with_opt::<rustc_middle[33747cc028c37340]::util::bug::opt_span_bug_fmt<rustc_span[174cbf46716f164]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  13:     0x7e247af4edfb - rustc_middle[33747cc028c37340]::ty::context::tls::with_context_opt::<rustc_middle[33747cc028c37340]::ty::context::tls::with_opt<rustc_middle[33747cc028c37340]::util::bug::opt_span_bug_fmt<rustc_span[174cbf46716f164]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  14:     0x7e2478a36840 - rustc_middle[33747cc028c37340]::util::bug::bug_fmt
  15:     0x7e247de0845f - rustc_codegen_ssa[7b70bfa2e61bfb0c]::back::metadata::elf_e_flags.cold
  16:     0x7e247d34df38 - rustc_codegen_ssa[7b70bfa2e61bfb0c]::back::metadata::create_object_file
  17:     0x7e247d34d782 - rustc_codegen_ssa[7b70bfa2e61bfb0c]::back::metadata::create_wrapper_file
  18:     0x7e247d0115ff - rustc_codegen_ssa[7b70bfa2e61bfb0c]::back::link::link_rlib
  19:     0x7e247cd8a686 - rustc_codegen_ssa[7b70bfa2e61bfb0c]::back::link::link_binary
  20:     0x7e247d1e50b1 - <rustc_interface[3c105e4e4d70b086]::queries::Linker>::link
  21:     0x7e247d1db3f9 - rustc_interface[3c105e4e4d70b086]::interface::run_compiler::<(), rustc_driver_impl[b04f6af5afbf5cf5]::run_compiler::{closure#0}>::{closure#1}
  22:     0x7e247cf5d452 - std[33b37f4690323d4d]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[3c105e4e4d70b086]::util::run_in_thread_with_globals<rustc_interface[3c105e4e4d70b086]::util::run_in_thread_pool_with_globals<rustc_interface[3c105e4e4d70b086]::interface::run_compiler<(), rustc_driver_impl[b04f6af5afbf5cf5]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  23:     0x7e247cf5dd34 - <<std[33b37f4690323d4d]::thread::Builder>::spawn_unchecked_<rustc_interface[3c105e4e4d70b086]::util::run_in_thread_with_globals<rustc_interface[3c105e4e4d70b086]::util::run_in_thread_pool_with_globals<rustc_interface[3c105e4e4d70b086]::interface::run_compiler<(), rustc_driver_impl[b04f6af5afbf5cf5]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[bab11496e675a0c0]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  24:     0x7e247cf5f12b - std::sys::pal::unix::thread::Thread::new::thread_start::h62b6440d2b872e88
  25:     0x7e2476c9caa4 - start_thread
                               at ./nptl/pthread_create.c:447:8
  26:     0x7e2476d29c3c - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78:0
  27:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/home/sven/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-core/rustc-ice-2025-04-01T19_47_32-21108.txt` to your bug report

note: compiler flags: --crate-type lib -C opt-level=s -C panic=abort -C linker-plugin-lto -C codegen-units=1 -C debuginfo=2 -Z force-unstable-if-unmarked

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `rustc-std-workspace-core` (lib)

Caused by:
  process didn't exit successfully: `/home/sven/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --crate-name rustc_std_workspace_core --edition=2024 /home/sven/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-core/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=190 --crate-type lib --emit=dep-info,metadata,link -C opt-level=s -C panic=abort -C linker-plugin-lto -C codegen-units=1 -C debuginfo=2 --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values())' -C metadata=2388fa32c093de1f -C extra-filename=-401e2a0431789085 --out-dir /home/sven/arduino/target/avr-atmega328p/release/deps --target /home/sven/arduino/avr-specs/avr-atmega328p.json -Z force-unstable-if-unmarked -L dependency=/home/sven/arduino/target/avr-atmega328p/release/deps -L dependency=/home/sven/arduino/target/release/deps --extern core=/home/sven/arduino/target/avr-atmega328p/release/deps/libcore-3cfc120e1c5069ee.rmeta --cap-lints allow` (exit status: 101)
warning: build failed, waiting for other jobs to finish...

thread 'rustc' panicked at compiler/rustc_codegen_ssa/src/back/metadata.rs:356:17:
compiler/rustc_codegen_ssa/src/back/metadata.rs:356:17: AVR CPU not explicitly specified
stack backtrace:
   0:     0x7aa943879b33 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::he2e6b0ecdb05c607
   1:     0x7aa944006051 - core::fmt::write::h610626c1c60da77c
   2:     0x7aa945466a91 - std::io::Write::write_fmt::h4e33684eb50b719c
   3:     0x7aa943879992 - std::sys::backtrace::BacktraceLock::print::h72b1875ec3ad25c3
   4:     0x7aa94387d47a - std::panicking::default_hook::{{closure}}::h2eb086ab7d432499
   5:     0x7aa94387cfff - std::panicking::default_hook::h4e505796ed0a3f8c
   6:     0x7aa9428f32b0 - std[33b37f4690323d4d]::panicking::update_hook::<alloc[b734503c5a26a59b]::boxed::Box<rustc_driver_impl[b04f6af5afbf5cf5]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7aa94387dcf3 - std::panicking::rust_panic_with_hook::h9e05a4a2b6a4fcb3
   8:     0x7aa942ee70b2 - std[33b37f4690323d4d]::panicking::begin_panic::<alloc[b734503c5a26a59b]::string::String>::{closure#0}
   9:     0x7aa942ee2326 - std[33b37f4690323d4d]::sys::backtrace::__rust_end_short_backtrace::<std[33b37f4690323d4d]::panicking::begin_panic<alloc[b734503c5a26a59b]::string::String>::{closure#0}, !>
  10:     0x7aa942edd907 - std[33b37f4690323d4d]::panicking::begin_panic::<alloc[b734503c5a26a59b]::string::String>
  11:     0x7aa942f73477 - rustc_middle[33747cc028c37340]::util::bug::opt_span_bug_fmt::<rustc_span[174cbf46716f164]::span_encoding::Span>::{closure#0}
  12:     0x7aa942f4ef8a - rustc_middle[33747cc028c37340]::ty::context::tls::with_opt::<rustc_middle[33747cc028c37340]::util::bug::opt_span_bug_fmt<rustc_span[174cbf46716f164]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  13:     0x7aa942f4edfb - rustc_middle[33747cc028c37340]::ty::context::tls::with_context_opt::<rustc_middle[33747cc028c37340]::ty::context::tls::with_opt<rustc_middle[33747cc028c37340]::util::bug::opt_span_bug_fmt<rustc_span[174cbf46716f164]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  14:     0x7aa940a36840 - rustc_middle[33747cc028c37340]::util::bug::bug_fmt
  15:     0x7aa945e0845f - rustc_codegen_ssa[7b70bfa2e61bfb0c]::back::metadata::elf_e_flags.cold
  16:     0x7aa94534df38 - rustc_codegen_ssa[7b70bfa2e61bfb0c]::back::metadata::create_object_file
  17:     0x7aa94534d782 - rustc_codegen_ssa[7b70bfa2e61bfb0c]::back::metadata::create_wrapper_file
  18:     0x7aa9450115ff - rustc_codegen_ssa[7b70bfa2e61bfb0c]::back::link::link_rlib
  19:     0x7aa944d8a686 - rustc_codegen_ssa[7b70bfa2e61bfb0c]::back::link::link_binary
  20:     0x7aa9451e50b1 - <rustc_interface[3c105e4e4d70b086]::queries::Linker>::link
  21:     0x7aa9451db3f9 - rustc_interface[3c105e4e4d70b086]::interface::run_compiler::<(), rustc_driver_impl[b04f6af5afbf5cf5]::run_compiler::{closure#0}>::{closure#1}
  22:     0x7aa944f5d452 - std[33b37f4690323d4d]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[3c105e4e4d70b086]::util::run_in_thread_with_globals<rustc_interface[3c105e4e4d70b086]::util::run_in_thread_pool_with_globals<rustc_interface[3c105e4e4d70b086]::interface::run_compiler<(), rustc_driver_impl[b04f6af5afbf5cf5]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  23:     0x7aa944f5dd34 - <<std[33b37f4690323d4d]::thread::Builder>::spawn_unchecked_<rustc_interface[3c105e4e4d70b086]::util::run_in_thread_with_globals<rustc_interface[3c105e4e4d70b086]::util::run_in_thread_pool_with_globals<rustc_interface[3c105e4e4d70b086]::interface::run_compiler<(), rustc_driver_impl[b04f6af5afbf5cf5]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[bab11496e675a0c0]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  24:     0x7aa944f5f12b - std::sys::pal::unix::thread::Thread::new::thread_start::h62b6440d2b872e88
  25:     0x7aa93ec9caa4 - start_thread
                               at ./nptl/pthread_create.c:447:8
  26:     0x7aa93ed29c3c - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78:0
  27:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: please attach the file at `/home/sven/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/rustc-ice-2025-04-01T19_47_21-20856.txt` to your bug report

note: compiler flags: --crate-type lib -C opt-level=s -C panic=abort -C linker-plugin-lto -C codegen-units=1 -C debuginfo=2 -Z force-unstable-if-unmarked

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `core` (lib)

Caused by:
  process didn't exit successfully: `/home/sven/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --crate-name core --edition=2024 /home/sven/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=190 --crate-type lib --emit=dep-info,metadata,link -C opt-level=s -C panic=abort -C linker-plugin-lto -C codegen-units=1 -C debuginfo=2 --warn=unexpected_cfgs --check-cfg 'cfg(bootstrap)' --check-cfg 'cfg(no_fp_fmt_parse)' --check-cfg 'cfg(stdarch_intel_sde)' --check-cfg 'cfg(target_feature, values("vector-enhancements-1"))' --check-cfg 'cfg(feature, values(any()))' --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values("debug_refcell", "debug_typeid", "optimize_for_size", "panic_immediate_abort"))' -C metadata=09e81d29c55612d2 -C extra-filename=-3cfc120e1c5069ee --out-dir /home/sven/arduino/target/avr-atmega328p/release/deps --target /home/sven/arduino/avr-specs/avr-atmega328p.json -Z force-unstable-if-unmarked -L dependency=/home/sven/arduino/target/avr-atmega328p/release/deps -L dependency=/home/sven/arduino/target/release/deps --cap-lints allow` (exit status: 101)

thread 'rustc' panicked at compiler/rustc_codegen_ssa/src/back/metadata.rs:356:17:
compiler/rustc_codegen_ssa/src/back/metadata.rs:356:17: AVR CPU not explicitly specified
stack backtrace:
   0:     0x7100f1a79b33 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::he2e6b0ecdb05c607
   1:     0x7100f2206051 - core::fmt::write::h610626c1c60da77c
   2:     0x7100f3666a91 - std::io::Write::write_fmt::h4e33684eb50b719c
   3:     0x7100f1a79992 - std::sys::backtrace::BacktraceLock::print::h72b1875ec3ad25c3
   4:     0x7100f1a7d47a - std::panicking::default_hook::{{closure}}::h2eb086ab7d432499
   5:     0x7100f1a7cfff - std::panicking::default_hook::h4e505796ed0a3f8c
   6:     0x7100f0af32b0 - std[33b37f4690323d4d]::panicking::update_hook::<alloc[b734503c5a26a59b]::boxed::Box<rustc_driver_impl[b04f6af5afbf5cf5]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7100f1a7dcf3 - std::panicking::rust_panic_with_hook::h9e05a4a2b6a4fcb3
   8:     0x7100f10e70b2 - std[33b37f4690323d4d]::panicking::begin_panic::<alloc[b734503c5a26a59b]::string::String>::{closure#0}
   9:     0x7100f10e2326 - std[33b37f4690323d4d]::sys::backtrace::__rust_end_short_backtrace::<std[33b37f4690323d4d]::panicking::begin_panic<alloc[b734503c5a26a59b]::string::String>::{closure#0}, !>
  10:     0x7100f10dd907 - std[33b37f4690323d4d]::panicking::begin_panic::<alloc[b734503c5a26a59b]::string::String>
  11:     0x7100f1173477 - rustc_middle[33747cc028c37340]::util::bug::opt_span_bug_fmt::<rustc_span[174cbf46716f164]::span_encoding::Span>::{closure#0}
  12:     0x7100f114ef8a - rustc_middle[33747cc028c37340]::ty::context::tls::with_opt::<rustc_middle[33747cc028c37340]::util::bug::opt_span_bug_fmt<rustc_span[174cbf46716f164]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  13:     0x7100f114edfb - rustc_middle[33747cc028c37340]::ty::context::tls::with_context_opt::<rustc_middle[33747cc028c37340]::ty::context::tls::with_opt<rustc_middle[33747cc028c37340]::util::bug::opt_span_bug_fmt<rustc_span[174cbf46716f164]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  14:     0x7100eec36840 - rustc_middle[33747cc028c37340]::util::bug::bug_fmt
  15:     0x7100f400845f - rustc_codegen_ssa[7b70bfa2e61bfb0c]::back::metadata::elf_e_flags.cold
  16:     0x7100f354df38 - rustc_codegen_ssa[7b70bfa2e61bfb0c]::back::metadata::create_object_file
  17:     0x7100f354d782 - rustc_codegen_ssa[7b70bfa2e61bfb0c]::back::metadata::create_wrapper_file
  18:     0x7100f32115ff - rustc_codegen_ssa[7b70bfa2e61bfb0c]::back::link::link_rlib
  19:     0x7100f2f8a686 - rustc_codegen_ssa[7b70bfa2e61bfb0c]::back::link::link_binary
  20:     0x7100f33e50b1 - <rustc_interface[3c105e4e4d70b086]::queries::Linker>::link
  21:     0x7100f33db3f9 - rustc_interface[3c105e4e4d70b086]::interface::run_compiler::<(), rustc_driver_impl[b04f6af5afbf5cf5]::run_compiler::{closure#0}>::{closure#1}
  22:     0x7100f315d452 - std[33b37f4690323d4d]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[3c105e4e4d70b086]::util::run_in_thread_with_globals<rustc_interface[3c105e4e4d70b086]::util::run_in_thread_pool_with_globals<rustc_interface[3c105e4e4d70b086]::interface::run_compiler<(), rustc_driver_impl[b04f6af5afbf5cf5]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  23:     0x7100f315dd34 - <<std[33b37f4690323d4d]::thread::Builder>::spawn_unchecked_<rustc_interface[3c105e4e4d70b086]::util::run_in_thread_with_globals<rustc_interface[3c105e4e4d70b086]::util::run_in_thread_pool_with_globals<rustc_interface[3c105e4e4d70b086]::interface::run_compiler<(), rustc_driver_impl[b04f6af5afbf5cf5]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[bab11496e675a0c0]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  24:     0x7100f315f12b - std::sys::pal::unix::thread::Thread::new::thread_start::h62b6440d2b872e88
  25:     0x7100ece9caa4 - start_thread
                               at ./nptl/pthread_create.c:447:8
  26:     0x7100ecf29c3c - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:78:0
  27:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: using internal features is not supported and expected to cause internal compiler errors when used incorrectly

note: please attach the file at `/home/sven/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/compiler_builtins-0.1.152/rustc-ice-2025-04-01T19_47_32-21114.txt` to your bug report

note: compiler flags: --crate-type lib -C opt-level=s -C panic=abort -C linker-plugin-lto -C codegen-units=1 -C debuginfo=2 -Z force-unstable-if-unmarked

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `compiler_builtins` (lib)

Caused by:
  process didn't exit successfully: `/home/sven/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --crate-name compiler_builtins --edition=2021 /home/sven/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/compiler_builtins-0.1.152/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=190 --crate-type lib --emit=dep-info,metadata,link -C opt-level=s -C panic=abort -C linker-plugin-lto -C codegen-units=1 -C debuginfo=2 --cfg 'feature="compiler-builtins"' --cfg 'feature="core"' --cfg 'feature="default"' --cfg 'feature="rustc-dep-of-std"' --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values("c", "cc", "compiler-builtins", "core", "default", "mangled-names", "mem", "no-asm", "no-f16-f128", "public-test-deps", "rustc-dep-of-std"))' -C metadata=4e3eedde57a1c75d -C extra-filename=-1b48e31772960dfa --out-dir /home/sven/arduino/target/avr-atmega328p/release/deps --target /home/sven/arduino/avr-specs/avr-atmega328p.json -Z force-unstable-if-unmarked -L dependency=/home/sven/arduino/target/avr-atmega328p/release/deps -L dependency=/home/sven/arduino/target/release/deps --extern core=/home/sven/arduino/target/avr-atmega328p/release/deps/librustc_std_workspace_core-401e2a0431789085.rmeta --cap-lints allow --cfg f16_enabled --cfg f128_enabled --cfg intrinsics_enabled --cfg arch_enabled --cfg optimizations_enabled --cfg 'feature="unstable-intrinsics"' --check-cfg 'cfg(__ashldi3, values("optimized-c"))' --check-cfg 'cfg(__ashlsi3, values("optimized-c"))' --check-cfg 'cfg(__ashrdi3, values("optimized-c"))' --check-cfg 'cfg(__ashrsi3, values("optimized-c"))' --check-cfg 'cfg(__bswapsi2, values("optimized-c"))' --check-cfg 'cfg(__bswapdi2, values("optimized-c"))' --check-cfg 'cfg(__bswapti2, values("optimized-c"))' --check-cfg 'cfg(__divdi3, values("optimized-c"))' --check-cfg 'cfg(__divsi3, values("optimized-c"))' --check-cfg 'cfg(__divmoddi4, values("optimized-c"))' --check-cfg 'cfg(__divmodsi4, values("optimized-c"))' --check-cfg 'cfg(__divmodsi4, values("optimized-c"))' --check-cfg 'cfg(__divmodti4, values("optimized-c"))' --check-cfg 'cfg(__lshrdi3, values("optimized-c"))' --check-cfg 'cfg(__lshrsi3, values("optimized-c"))' --check-cfg 'cfg(__moddi3, values("optimized-c"))' --check-cfg 'cfg(__modsi3, values("optimized-c"))' --check-cfg 'cfg(__muldi3, values("optimized-c"))' --check-cfg 'cfg(__udivdi3, values("optimized-c"))' --check-cfg 'cfg(__udivmoddi4, values("optimized-c"))' --check-cfg 'cfg(__udivmodsi4, values("optimized-c"))' --check-cfg 'cfg(__udivsi3, values("optimized-c"))' --check-cfg 'cfg(__umoddi3, values("optimized-c"))' --check-cfg 'cfg(__umodsi3, values("optimized-c"))' --check-cfg 'cfg(__aarch64_cas1_relax, values("optimized-c"))' --check-cfg 'cfg(__aarch64_cas1_acq, values("optimized-c"))' --check-cfg 'cfg(__aarch64_cas1_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_cas1_acq_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_cas2_relax, values("optimized-c"))' --check-cfg 'cfg(__aarch64_cas2_acq, values("optimized-c"))' --check-cfg 'cfg(__aarch64_cas2_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_cas2_acq_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_cas4_relax, values("optimized-c"))' --check-cfg 'cfg(__aarch64_cas4_acq, values("optimized-c"))' --check-cfg 'cfg(__aarch64_cas4_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_cas4_acq_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_cas8_relax, values("optimized-c"))' --check-cfg 'cfg(__aarch64_cas8_acq, values("optimized-c"))' --check-cfg 'cfg(__aarch64_cas8_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_cas8_acq_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_cas16_relax, values("optimized-c"))' --check-cfg 'cfg(__aarch64_cas16_acq, values("optimized-c"))' --check-cfg 'cfg(__aarch64_cas16_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_cas16_acq_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldadd1_relax, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldadd1_acq, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldadd1_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldadd1_acq_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldadd2_relax, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldadd2_acq, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldadd2_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldadd2_acq_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldadd4_relax, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldadd4_acq, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldadd4_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldadd4_acq_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldadd8_relax, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldadd8_acq, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldadd8_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldadd8_acq_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldclr1_relax, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldclr1_acq, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldclr1_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldclr1_acq_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldclr2_relax, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldclr2_acq, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldclr2_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldclr2_acq_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldclr4_relax, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldclr4_acq, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldclr4_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldclr4_acq_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldclr8_relax, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldclr8_acq, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldclr8_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldclr8_acq_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldeor1_relax, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldeor1_acq, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldeor1_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldeor1_acq_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldeor2_relax, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldeor2_acq, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldeor2_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldeor2_acq_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldeor4_relax, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldeor4_acq, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldeor4_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldeor4_acq_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldeor8_relax, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldeor8_acq, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldeor8_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldeor8_acq_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldset1_relax, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldset1_acq, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldset1_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldset1_acq_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldset2_relax, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldset2_acq, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldset2_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldset2_acq_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldset4_relax, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldset4_acq, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldset4_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldset4_acq_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldset8_relax, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldset8_acq, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldset8_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_ldset8_acq_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_swp1_relax, values("optimized-c"))' --check-cfg 'cfg(__aarch64_swp1_acq, values("optimized-c"))' --check-cfg 'cfg(__aarch64_swp1_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_swp1_acq_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_swp2_relax, values("optimized-c"))' --check-cfg 'cfg(__aarch64_swp2_acq, values("optimized-c"))' --check-cfg 'cfg(__aarch64_swp2_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_swp2_acq_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_swp4_relax, values("optimized-c"))' --check-cfg 'cfg(__aarch64_swp4_acq, values("optimized-c"))' --check-cfg 'cfg(__aarch64_swp4_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_swp4_acq_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_swp8_relax, values("optimized-c"))' --check-cfg 'cfg(__aarch64_swp8_acq, values("optimized-c"))' --check-cfg 'cfg(__aarch64_swp8_rel, values("optimized-c"))' --check-cfg 'cfg(__aarch64_swp8_acq_rel, values("optimized-c"))' --check-cfg 'cfg(target_feature, values("vis3"))' --check-cfg 'cfg(feature, values("checked"))' --check-cfg 'cfg(assert_no_panic)' --check-cfg 'cfg(f16_enabled)' --check-cfg 'cfg(f128_enabled)' --check-cfg 'cfg(thumb)' --check-cfg 'cfg(thumb_1)' --check-cfg 'cfg(intrinsics_enabled)' --check-cfg 'cfg(arch_enabled)' --check-cfg 'cfg(optimizations_enabled)' --check-cfg 'cfg(feature, values("unstable-public-internals"))' --check-cfg 'cfg(optimizations_enabled)' --check-cfg 'cfg(x86_no_sse)' --check-cfg 'cfg(feature, values("mem-unaligned"))' --check-cfg 'cfg(kernel_user_helpers)'` (exit status: 101)

```

i dont know exactly what to put here. i have a pretty much empty arduino uno project. it works on a very similar computer. i've tried installing all the things github, stackoverflow and reddit have told me to install but nothing works. ask me if you need more details

**Comment by jfrimmel** [comment]
The ICE should not happen, of course, but the error message shows the cause and hints to the resolution: the CPU is not set, which apparently is required since the introduction of the the `avr-none`-target. 
Adding the `-Ctarget-cpu`-flag should solve the issue (altough the ICE should be fixed nevertheless):
```shell
RUSTFLAGS='-Ctarget-cpu=atmega328p' cargo build --release --target=avr-specs/avr-atmega328p.json
```

@rustbot label +O-AVR

**Comment by coolCucumber-cat** [comment]
@jfrimmel it didn't work at first and i was still getting weird error messages, but i removed some environment variables (PKG_CONFIG_PATH and some others, related to libudev) that i was told to add and now it works. the ICE should still be fixed though

**Comment by coolCucumber-cat** [comment]
it also only works when:
`panic-halt = "0.2.0"` and `[build-dependencies]
proc-macro2 = "=1.0.79"` (see: https://github.com/Rahix/avr-hal/issues/537)

**Comment by EvansJahja** [comment]
Put this file: `.cargo/config.toml`

```toml
[build]
target = 'avr-none'
rustflags = ["-C", "target-cpu=atmega328p"]

[unstable]
build-std = ["core", "alloc"]
```

In ``.cargo/config.toml``, **NOT** `Cargo.toml`

then build with `cargo build --release` (no need to provide json)

**Comment by tgross35** [comment]
@rustbot label +E-Easy +E-help-wanted

This should be reasonably straightforward to fix since we already do this for the `amdgcn-amd-amdhsa`, whatever logic that is just needs to be applied to AVR as well.

```text
$ cargo check --target=amdgcn-amd-amdhsa -Zbuild-std=core
   Compiling core v0.0.0 (lib/rustlib/src/rust/library/core)
   Compiling compiler_builtins v0.1.160 (lib/rustlib/src/rust/library/compiler-builtins/compiler-builtins)
error: target requires explicitly specifying a cpu with `-C target-cpu`

error: could not compile `core` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `compiler_builtins` (lib) due to 1 previous error
```
