### ISSUE TITLE
Rustdoc links to std library types pass through the facade

### ISSUE THREAD

**Issue by tomjakubowski** [rust-lang/rust#22083]
As an example, generate documentation for this:

```rust
#![crate_type="lib"]

pub trait Trait { }

impl<T> Trait for Vec<T> { }
```

On the docs for the `Trait` trait, there will be an Implementors section like this:

<ul class="item-list" id="implementors-list">
    <li><a class="stability Unmarked" title="No stability level"></a><code>impl&lt;'a, T&gt; <a class="trait" href="../foo/trait.Trait.html" title="foo::Trait">Trait</a> for <a class="struct" href="http://doc.rust-lang.org/nightly/collections/vec/struct.Vec.html" title="collections::vec::Vec">Vec</a>&lt;T&gt;</code></li>
</ul>

Note that the `Vec` link goes to docs for the *`collections`* crate and not to docs for `std`. Since the 1.0 release will not host documentation for crates behind the facade, this will lead to broken documentation links for third-party crates.

**Comment by steveklabnik** [comment]
Triage: this is still true today.

**Comment by lukaramu** [comment]
Triage: looks like this is fixed (see e.g. [here][1] or [here][2]).

[1]: https://doc.rust-lang.org/std/collections/binary_heap/struct.BinaryHeap.html#method.into_vec
[2]: https://doc.rust-lang.org/std/cmp/trait.PartialEq.html#implementors

**Comment by steveklabnik** [comment]
@lukaramu in the second link, it still looks like it's linking to libcollections, not to libstd?

**Comment by lukaramu** [comment]
@steveklabnik seems like I was too superficial, my bad...

Upon taking a closer look, there seem to be multiple components:

A lot of trait implementors are duplicate, this seems to be #25061. The initial entries (mostly, see below) link within libstd (which led me to believe that this was fixed); the entries that are generated dynamically (everything after `impl PartialEq for SystemTime`) bypass the facade, e.g. Box/Arc/Rc to liballoc, DecodeUtf16Error to libstd_unicode, etc.

Then, even the *not* dynamically generated entry for the implementation by EnumSet links to libcollections, which in some way makes sense as it isn't in std::collections anyway.

**Comment by AlexArgoAi** [comment]
This is still a problem today.

Documenting this library:
```rust
use std::rc::Rc;

pub fn foo() -> Rc<()> {
    Rc::new(())
}
```
will produce a link to https://doc.rust-lang.org/nightly/alloc/rc/struct.Rc.html rather than https://doc.rust-lang.org/nightly/std/rc/struct.Rc.html.
