### ISSUE TITLE
Send + Sync and Sync + Send are distinct valid types

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#33140]
## STR

``` Rust
#![feature(specialization)]

trait Teq<U:?Sized> {
    fn types_eq() -> &'static str;
}

impl<U:?Sized> Teq<U> for U {
    fn types_eq() -> &'static str { "types are equal" }
}

impl<U:?Sized, V:?Sized> Teq<U> for V {
    default fn types_eq() -> &'static str { "types differ" }
}

fn main() {
    println!("{}", <Send+Sync as Teq<Sync+Send>>::types_eq());
}
```
## Expected Result

This should not compile, or should print "types are equal"
## Actual Result

This prints "types differ".

**Comment by arielb1** [comment]
I *think* this should be fixed to not compiling, right?

**Comment by durka** [comment]
Why should they be different?

**Comment by arielb1** [comment]
They should be the same type (rather, this code should not compile) The bug is that they are different.

**Comment by durka** [comment]
I still don't understand, sorry... what compile error do you expect? If they were the same type, it would print "types are equal"? Are you saying that neither of them should be accepted as a type?

**Comment by arielb1** [comment]
@durka 

I am going to write a PR that will make neither of them be accepted as a type.

**Comment by durka** [comment]
Okay... maybe in the PR you can explain why, as I keep asking? FWIW, `Any + Send + Sync` and `Any + Sync + Send` are equal using your code above.

**Comment by arielb1** [comment]
The problem type is `Sync + Send` *without any additional trait*. `Any + Sync + Send` is a perfectly good type, and will not be removed.

**Comment by durka** [comment]
Is it because they are both marker traits? Or both auto traits?

**Comment by cyplo** [comment]
Hello ! Any changes on this one ?

**Comment by RalfJung** [comment]
The two types differing it at least consistent with this being rejected due to a type mismatch:
```rust
fn foo(x: Box<Send+Sync>) -> Box<Sync+Send> { x }
```
