### ISSUE TITLE
Use BTreeMap with u128 values for sparse bit sets/"vectors" (in dataflow etc.).

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#47575]
According to our current implementation of B-trees:
https://github.com/rust-lang/rust/blob/5965b790142eff7a8546e947914e7a8e00c61575/src/liballoc/btree/node.rs#L53-L55
it would appear that up to `11` key-value pairs can be stored in each node.

For `u128` values representing `128` set elements each, `1408` set elements can be stored in a single allocation, with an overhead of around 50% compared to `Vec<u128>` in the dense case.

Such sparse bitsets would be really useful for (e.g. dataflow) analysis algorithms, in situations where the bitset elements tend to be localized, with multi-"word" gaps in between local groups.

cc @nikomatsakis @pnkfelix

**Comment by nikomatsakis** [comment]
Is the idea that the key would be `index >> 7` and the value would be a bitset of size 128? i.e., so to tell if something is there, we compute the key and then mask the resulting value?

**Comment by eddyb** [comment]
@nikomatsakis That's pretty much it, yes. Here's what I've been playing with so far:
<details>

```rust
// FIXME(eddyb) move to rustc_data_structures.
#[derive(Clone)]
pub struct SparseBitSet<I: Idx> {
    map: BTreeMap<u32, u128>,
    _marker: PhantomData<I>,
}

fn key_and_mask<I: Idx>(index: I) -> (u32, u128) {
    let index = index.index();
    let key = index / 128;
    let key_u32 = key as u32;
    assert_eq!(key_u32 as usize, key);
    (key_u32, 1 << (index % 128))
}

impl<I: Idx> SparseBitSet<I> {
    pub fn new() -> Self {
        SparseBitSet {
            map: BTreeMap::new(),
            _marker: PhantomData
        }
    }

    pub fn contains(&self, index: I) -> bool {
        let (key, mask) = key_and_mask(index);
        self.map.get(&key).map_or(false, |bits| (bits & mask) != 0)
    }

    pub fn insert(&mut self, index: I) -> bool {
        let (key, mask) = key_and_mask(index);
        let bits = self.map.entry(key).or_insert(0);
        let old_bits = *bits;
        let new_bits = old_bits | mask;
        *bits = new_bits;
        new_bits != old_bits
    }

    pub fn remove(&mut self, index: I) -> bool {
        let (key, mask) = key_and_mask(index);
        if let Some(bits) = self.map.get_mut(&key) {
            let old_bits = *bits;
            let new_bits = old_bits & !mask;
            *bits = new_bits;
            new_bits != old_bits
        } else {
            false
        }
    }

    pub fn iter<'a>(&'a self) -> impl Iterator<Item = I> + 'a {
        self.map.iter().flat_map(|(&key, &bits)| {
            let base = key as usize * 128;
            (0..128).filter_map(move |i| {
                if (bits & (1 << i)) != 0 {
                    Some(I::new(base + i))
                } else {
                    None
                }
            })
        })
    }
}
```
</details>

**Comment by nikomatsakis** [comment]
Makes sense. I wonder if it would be useful in NLL too.

**Comment by eternaleye** [comment]
One thing that might be worth considering is using [binmaps](http://www.ds.ewi.tudelft.nl/fileadmin/pds/reports/2011/PDS-2011-005.pdf).

**Comment by eddyb** [comment]
We should also benchmark "sparse bit matrices" with `BTreeMap` (or `FxHashMap`) keys that also contain the "row" number, not just the upper bits of the "column" number.
They might prove more efficient than `Vec<BTreeMap<u32, u128>>`.

**Comment by eddyb** [comment]
I've added a "chunked" API to my `SparseBitSet`, in the hope of 128x+ perf wins:
<details>

```rust
// FIXME(eddyb) move to rustc_data_structures.
#[derive(Clone)]
pub struct SparseBitSet<I: Idx> {
    chunk_bits: BTreeMap<u32, u128>,
    _marker: PhantomData<I>,
}

#[derive(Copy, Clone)]
pub struct SparseChunk<I> {
    key: u32,
    bits: u128,
    _marker: PhantomData<I>,
}

impl<I: Idx> SparseChunk<I> {
    pub fn one(index: I) -> Self {
        let index = index.index();
        let key_usize = index / 128;
        let key = key_usize as u32;
        assert_eq!(key as usize, key_usize);
        SparseChunk {
            key,
            bits: 1 << (index % 128),
            _marker: PhantomData
        }
    }

    pub fn any(&self) -> bool {
        self.bits != 0
    }

    pub fn iter(&self) -> impl Iterator<Item = I> {
        let base = self.key as usize * 128;
        let mut bits = self.bits;
        (0..128).map(move |i| {
            let current_bits = bits;
            bits >>= 1;
            (i, current_bits)
        }).take_while(|&(_, bits)| bits != 0)
          .filter_map(move |(i, bits)| {
            if (bits & 0) != 0 {
                Some(I::new(base + i))
            } else {
                None
            }
        })
    }
}

impl<I: Idx> SparseBitSet<I> {
    pub fn new() -> Self {
        SparseBitSet {
            chunk_bits: BTreeMap::new(),
            _marker: PhantomData
        }
    }

    pub fn capacity(&self) -> usize {
        self.chunk_bits.len() * 128
    }

    pub fn contains_chunk(&self, chunk: SparseChunk<I>) -> SparseChunk<I> {
        SparseChunk {
            bits: self.chunk_bits.get(&chunk.key).map_or(0, |bits| bits & chunk.bits),
            ..chunk
        }
    }

    pub fn insert_chunk(&mut self, chunk: SparseChunk<I>) -> SparseChunk<I> {
        let bits = self.chunk_bits.entry(chunk.key).or_insert(0);
        let old_bits = *bits;
        let new_bits = old_bits | chunk.bits;
        *bits = new_bits;
        let changed = new_bits ^ old_bits;
        SparseChunk {
            bits: changed,
            ..chunk
        }
    }

    pub fn remove_chunk(&mut self, chunk: SparseChunk<I>) -> SparseChunk<I> {
        let changed = if let Some(bits) = self.chunk_bits.get_mut(&chunk.key) {
            let old_bits = *bits;
            let new_bits = old_bits & !chunk.bits;
            *bits = new_bits;
            // FIXME(eddyb) maybe remove entry if now `0`.
            new_bits ^ old_bits
        } else {
            0
        };
        SparseChunk {
            bits: changed,
            ..chunk
        }
    }

    pub fn clear(&mut self) {
        for bits in self.chunk_bits.values_mut() {
            *bits = 0;
        }
    }

    pub fn chunks<'a>(&'a self) -> impl Iterator<Item = SparseChunk<I>> + 'a {
        self.chunk_bits.iter().map(|(&key, &bits)| {
            SparseChunk {
                key,
                bits,
                _marker: PhantomData
            }
        })
    }

    pub fn contains(&self, index: I) -> bool {
        self.contains_chunk(SparseChunk::one(index)).any()
    }

    pub fn insert(&mut self, index: I) -> bool {
        self.insert_chunk(SparseChunk::one(index)).any()
    }

    pub fn remove(&mut self, index: I) -> bool {
        self.remove_chunk(SparseChunk::one(index)).any()
    }

    pub fn iter<'a>(&'a self) -> impl Iterator<Item = I> + 'a {
        self.chunks().flat_map(|chunk| chunk.iter())
    }
}
```
</details>

cc @spastorino

**Comment by spastorino** [comment]
Done here https://github.com/rust-lang/rust/pull/48245

**Comment by tamird** [comment]
Should this be closed, now?

**Comment by nikomatsakis** [comment]
Maybe? There are still some places we could use sparse sets that we are not today, I suppose.

**Comment by Mark-Simulacrum** [comment]
I'm going to go ahead and close. There's been a bunch of iterations on various sparse vs. dense tradeoffs throughout the compiler (particularly in the MIR-related code), I don't think a generic tracking issue remains useful.
