### ISSUE TITLE
No console colors on Windows 7

### ISSUE THREAD

**Issue by jminer** [rust-lang/rust#55769]
I just updated Rust at work, and now rustc has no colors in the console (Cargo still does). I'm using Windows 7 64-bit with Rust MSVC 32-bit. I tried 1.29 stable and it worked, but 1.30 stable and the latest nightly don't work. I have tried both cmd.exe and PowerShell and both look the same. This is a big regression in usability, so I'll probably downgrade back to a working version.

![rustc_no_colors](https://user-images.githubusercontent.com/824671/48156111-39f10700-e292-11e8-8f45-df4fe8fda472.png)

**Comment by kennytm** [comment]
@alexcrichton previously i did have tested on cmd.exe, but i haven't followed the recent changes which might have broken it

**Comment by alexcrichton** [comment]
Hm ok, that's worrisome! If https://github.com/rust-lang/rust/pull/55788 doesn't do the trick I can try to investigate later, but it'll be quite awhile before I have a windows computer to test on again

**Comment by alexcrichton** [comment]
For posterity there was [some discussion](https://github.com/rust-lang/rust/pull/55788#issuecomment-437632954) of why this isn't actually fixed on nightly right now, and @kennytm [has a PR to `termcolor`](https://github.com/BurntSushi/termcolor/pull/10) which should fix this

**Comment by MSxDOS** [comment]
Any chance this is getting fixed in the nearest future?

**Comment by mati865** [comment]
@MSxDOS I pinged `termcolor` author and he is reviewing PR mentioned above so this should get fixed on nightly soon.

**Comment by kennytm** [comment]
Nah we still need to go through the package release and update Cargo.lock  processes 🙃

**Comment by phansch** [comment]
When this gets fixed, is there a possibility of adding some sort of UI test for this? This would be helpful for ensuring colors continue to work, when implementing https://github.com/rust-lang/rust/issues/59346

**Comment by moxian** [comment]
`termcolor-1.0.5` was released containing the fix.
I thought I'd update Cargo.lock and PR the change, but I've built rustc with termcolor-1.0.5. and I still can't see the rustc color output when run by cargo. So either I did something wrong when updating/rebuilding rustc, or https://github.com/BurntSushi/termcolor/pull/10 didn't fix the issue...

**Comment by ehuss** [comment]
@moxian it should work, but there is a bug in Cargo where colors are not working correctly, so that's why I have not updated things here, yet.  I filed https://github.com/kennytm/fwdansi/issues/1 but I have not heard back from @kennytm, yet.

**Comment by ehuss** [comment]
This should be fixed on the latest nightly (2020-07-31) via https://github.com/rust-lang/cargo/pull/8540 and https://github.com/rust-lang/rust/pull/74923.
