### ISSUE TITLE
regression: assertion failed: data.is_empty()

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#70445]
https://crater-reports.s3.amazonaws.com/beta-1.43-1/beta-2020-03-12/reg/in_stream-0.0.45-alpha1/log.txt
https://crater-reports.s3.amazonaws.com/beta-1.43-1/beta-2020-03-12/reg/jnix-0.2.1/log.txt

**Comment by Centril** [comment]
cc @matthewjasper

**Comment by matthewjasper** [comment]
I think that this is fixed by #69591

**Comment by Mark-Simulacrum** [comment]
The relevant PR, #69591, is pending in a beta backport (#70742) -- once that lands and is released, we can easily test this.

**Comment by pnkfelix** [comment]
@Mark-Simulacrum I do not see #69591 listed in the version of PR #70742 that landed?

**Comment by pnkfelix** [comment]
(and, in case its unclear: I also tested against `beta-2020-04-04`; the bug persists. Which is not surprising since it seems like the backport of PR #69591 has not yet landed.)

**Comment by Mark-Simulacrum** [comment]
Ah, so I see why I missed it for the last couple backports: GitHub (?) changed something and now https://github.com/rust-lang/rust/pulls?q=is%3Apr+label%3Abeta-accepted+is%3Aclosed+label%3Abeta-nominated no longer shows any PRs.

I suspect this means we'll now need to use a search like https://github.com/rust-lang/rust/pulls?q=is%3Apr+label%3Abeta-nominated and then manually select just the accepted ones :/

cc @pietroalbini -- could we bring this up with GH at our next call perhaps?

**Comment by pietroalbini** [comment]
@Mark-Simulacrum I can, but the next call is in two weeks. Have you tried contacting GitHub Support in the meantime?

**Comment by Mark-Simulacrum** [comment]
Alright prepared a PR for it here: https://github.com/rust-lang/rust/pull/70848 and approved that.

@pietroalbini I don't think it's urgent, and I don't have time to write up an explanation of it, so was trying to pawn off work :)

**Comment by matthewjasper** [comment]
Is this fixed?

**Comment by Mark-Simulacrum** [comment]
I think so, this was just tracking the beta regression (and from a couple cycles ago) and the backport went in. Closing.
