### ISSUE TITLE
Duplicate crate macros failing to differentiate

### ISSUE THREAD

**Issue by LucioFranco** [rust-lang/rust#71259]
Here is a reproduction:

https://github.com/LucioFranco/rustc-duplicate-macro-bug/

I've added comments on how to trigger the bug. But it looks like if we have one crate but two versions imported into the same project. Aka using cargo's rename feature, then rust picks up that if we use one of the macros that the other one even if its from a different version is the same. Commenting out the tower01 `assert_request_eq` allows the second one to compile properly. If its not commented out the `tower03` version will fail to compile because it is attempting to use the `tower01` version which doesn't await the inner future.

### Meta

This happens currently on `rustc 1.42.0 (b8cedc004 2020-03-09)` but not on a newer nightly `cargo 1.44.0-nightly (390e8f245 2020-04-07)`. So this has probably been fixed but I couldn't find any issue for this specific problem.

</p>
</details>

**Comment by LucioFranco** [comment]
Since, this has been fixed on nightly, I assume we can close it. I thought I'd open for reference reasons.

**Comment by jonas-schievink** [comment]
Sounds like something @petrochenkov might know about

**Comment by petrochenkov** [comment]
No idea how this happened and I don't remember fixing anything similar.

This look like a serious bug, it would be great to bisect this to find out what made it disappear.
Perhaps it was just masked and not really fixed.

**Comment by robjtede** [comment]
bisect-rustc points to 15812785344d913d779d9738fe3cca8de56f71d5

**Comment by petrochenkov** [comment]
@robjtede 
Thanks!

Before #66364 in this line

https://github.com/rust-lang/rust/pull/66364/files#diff-2b18e583c8286c5f266dcc0aea004e91L426

two `assert_request_eq` macros had the same `source_name` so the second macro hit the cache inside `new_source_file` and returned the string for the first macro instead of its own.

So #66364 indeed fixed the issue and not masked it.

The condition for the test is that two library crates should have the same name and should export macros with the same name.
Then any crate using these two macros together will hit the issue.

**Comment by Enselic** [comment]
This issue will be closed by https://github.com/rust-lang/rust/pull/150083 which adds a test.

@rustbot claim
