### ISSUE TITLE
Can't import core::arch::arm::int32x4_t;

### ISSUE THREAD

**Issue by jrmuizel** [rust-lang/rust#76773]
I tried this code:

```rust
#![feature(stdsimd)]
use core::arch::arm::int32x4_t;
//use core_arch::arch::arm::int32x4_t;

pub fn main() {
    println!("Hello, world!");
}
```
I tried building with `RUSTFLAGS='-C target-feature=+v7,+neon' cargo build --target arm-linux-androideabi`
and I get 
```
error[E0432]: unresolved import `core::arch::arm::int32x4_t`
 --> src/lib.rs:2:5
  |
2 | use core::arch::arm::int32x4_t;
  |     ^^^^^^^^^^^^^^^^^---------
  |     |                |
  |     |                help: a similar name exists in the module: `int16x2_t`
  |     no `int32x4_t` in `arch::arm`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
```
If I use the core_arch crate directly it successfully finds the type.

### Meta

`rustc --version --verbose`:
```
rustc 1.48.0-nightly (9b4154193 2020-09-14)
binary: rustc
commit-hash: 9b4154193e8471f36b1a9e781f1ef7d492fc6a6c
commit-date: 2020-09-14
host: x86_64-apple-darwin
release: 1.48.0-nightly
LLVM version: 11.0
```

@Amanieu

**Comment by Amanieu** [comment]
This should be fixed once the stdarch module is updated in nightly. It's because libcore was compiled without the neon feature and this causes all the neon types to be missing.

**Comment by jrmuizel** [comment]
Ah. Great.

**Comment by Amanieu** [comment]
Actually the nightly should be out now, try updating.

**Comment by jrmuizel** [comment]
With the updated nightly `rustc 1.48.0-nightly (6af1bdda5 2020-09-15)` I still have the same problem.

**Comment by Amanieu** [comment]
In this case I think it's because libcore wasn't compiled with the `v7` feature. Try using `armv7-linux-androideabi` instead.

**Comment by jrmuizel** [comment]
Yes, that fixed it.
